using System.Runtime.Serialization;
using System.Text.Json.Serialization;

namespace Enjna.AppStoreConnectApi.Models.Enums;

/// <summary>
/// Whether the App Store promotes a win-back offer on your behalf.
/// </summary>
/// <seealso href="https://developer.apple.com/documentation/appstoreconnectapi/winbackoffer/attributes"/>
[JsonConverter(typeof(JsonEnumMemberConverter<WinBackOfferPromotionIntent>))]
public enum WinBackOfferPromotionIntent
{
    /// <summary>
    /// Represents a value not yet supported by this version of the library.
    /// </summary>
    _Unmapped,

    /// <summary>
    /// The App Store doesn't promote the offer. You present it yourself, in your app.
    /// </summary>
    [EnumMember(Value = "NOT_PROMOTED")]
    NotPromoted,

    /// <summary>
    /// The App Store promotes the offer with the assets it generates from your subscription's
    /// metadata.
    /// </summary>
    [EnumMember(Value = "USE_AUTO_GENERATED_ASSETS")]
    UseAutoGeneratedAssets
}
